from .get_face_parts import get_mask
from .Ordinary_Procrustes_Analysis import OPA
from .poisson_img_editing import poisson_edit
from .cut_up_face import cut_faces
from .fusion import fuse
from .face_detection import detection
from .img2video import img2video
from .get_features import return_features
from .color_detect import color_detect
from .database import watchdatabase
from .create_qr import make_qr_code
from .create_qr import make_qr_code_easy
from .create_qr import make_qr_code_with_icon
from .create_qr import decode_qr_code